### PR TITLE
update holopin badge

### LINKED ISSUE #164: Update the holopin.yaml to use the sdk badge
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqfdv4x24910fl5n4iwu5oa) for this repo:

```yaml
organization: dapr
defaultSticker: clrqfdv4x24910fl5n4iwu5oa
stickers:
  -
    id: clrqfdv4x24910fl5n4iwu5oa
    alias: sdk-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---

Please label this as a __good first issue__.

### PR DESCRIPTION
**Pull request by KentHsu**
# Description

The yaml file to award SDK badges had been updated such that each contributor can be awarded with a SDK badge for their contribution to this repo.

## Issue reference

This PR will close #164

## Checklist

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation

### CODE REVIEW

**Review by mikeee — APPROVED** [review]
lgtm - thanks for picking this up so quickly!

**Comment by mikeee** [comment]
@holopin-bot @KentHsu

**Comment by mikeee** [comment]
@holopin-bot @KentHsu

**Comment by marcduiker** [comment]
@holopin-bot @KentHsu

**Comment by KentHsu** [comment]
Glad to see it works! Thank you @marcduiker

**Pull request merged**
