### PR TITLE
Feature: Enable query state API

### PR DESCRIPTION
**Pull request by ruokun-niu**
The query state API is an existing API that is currently in the Alpha stage. Currently, this capability is available in some other SDKs, e.g. the [JavaScript SDK](https://github.com/dapr/rust-sdk/blob/8db69d84fed6240c85528ae7447f8df3587c68f5/dapr/proto/runtime/v1/dapr.proto#L293). In the Rust SDK, we cannot utilize the query API to fetch specific states in the `Client` Struct.

This PR utilizes the existing proto messages `QueryStateRequest` and `QueryStateResponse` to enable state querying. I have added a new function called `query_state_alpha1()` that takes in two parameters: `store_name` and `query` and an optional parameter: `metadata`.

The query can be defined using `serde_json::json`

Example:
```rust
let mut client = dapr::Client::<dapr::client::TonicClient>::connect(addr).await?;


let query_condition = json!({
    "filter": {
        "EQ": { "state": "CA" }
    },
    "sort": [
        {
            "key": "person.id",
            "order": "DESC"
        }
    ]
});

let response_result = match client.query_state_alpha1("statestore", query_condition, None).await {
    Ok(response) => response.results,
    Err(e) => {
        println!("Error: {:?}", e);
        return Ok(());
    }
};
```

Issue #115

### CODE REVIEW

**Comment by mikeee** [comment]
Looks good, I have two questions:

1. Does this work with redis-stack? If simple enough, this could be a good way to stand up a test env (as an alternative to mongodb)
2. Could/should the two queries be combined into one app?

**Comment by ruokun-niu** [comment]
Hi @mikeee, thanks for the comments and sorry for my late response. I'll take a look into this and update the PR

**Comment by mikeee** [comment]
No worries, I can update and get this pushed through 👍

**Comment by ruokun-niu** [comment]
That would be great! Thanks :)

**Review by mikeee — APPROVED** [review]
lgtm

**Comment by mikeee** [comment]
Thanks for the contribution @ruokun-niu, much appreciated 😄

**Comment by ruokun-niu** [comment]
Thanks for the review and help!

**Comment by marcduiker** [comment]
@holopin-bot @ruokun-niu Thank you!

**Pull request merged**
