### PR TITLE
Derive Clone for Client

### PR DESCRIPTION
**Pull request by c-thiel**
Fixes: https://github.com/dapr/rust-sdk/issues/91

I had to change some imports to avoid ambiguous name errors I got, probably due to a new rust version.
Feel free to remove them if this is not needed.

### CODE REVIEW

**Comment by zedgell** [comment]
@c-thiel I have not personally hit the name errors on 1.68 which is the latest stable version. What version did you hit this issue on?

**Comment by c-thiel** [comment]
Also on 1.68. Maybe those also took effect due to some stricter import rules. My VS-Code Rust Analyzer is also complaining.
Feel free to remove them. The derive really is much more important :)

**Comment by c-thiel** [comment]
@zedgell, I double checked my setup and my build failed due to some workspace settings.
I reverted my other changes so that this PR really just contains this one missing line.

**Comment by cscetbon** [comment]
@c-thiel @zedgell is the fact those commits are not signed the main blocker of this PR ?

**Comment by mikeee** [comment]
@c-thiel Hey👋 would you be able to signoff your commits so I can merge?

**Comment by mikeee** [comment]
Closing as the changes have been usurped.

**Pull request closed without merging**
